// Date: 6/19/2014 8:57:36 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package ft.fct.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelForgeold extends ModelBase{
  //fields
    ModelRenderer Base1;
    ModelRenderer Base2;
    ModelRenderer Base3;
    ModelRenderer Base4;
    ModelRenderer Base5;
    ModelRenderer Base6;
    ModelRenderer Base7;
    ModelRenderer Base8;
    ModelRenderer Base9;
    ModelRenderer Base10;
    ModelRenderer Base11;
    ModelRenderer Base12;
    ModelRenderer Base13;
    ModelRenderer Base14;
    ModelRenderer Base15;
    ModelRenderer Base16;
    ModelRenderer Base17;
    ModelRenderer Base18;
    ModelRenderer Base19;
    ModelRenderer Base20;
    ModelRenderer Base21;
    ModelRenderer Base22;
    ModelRenderer Base23;
    ModelRenderer Base24;
    ModelRenderer Base25;
    ModelRenderer Base26;
    ModelRenderer Base27;
    ModelRenderer Base28;
    ModelRenderer Base29;
    ModelRenderer Base30;
    ModelRenderer Base31;
    ModelRenderer Base32;
    ModelRenderer Base33;
    ModelRenderer Base34;
    ModelRenderer Hammer1;
    ModelRenderer Hammer2;
    ModelRenderer Hammer3;
  
  public ModelForgeold()
  {
    textureWidth = 512;
    textureHeight = 512;
    
      Base1 = new ModelRenderer(this, 0, 0);
      Base1.addBox(0F, 0F, 0F, 2, 1, 26);
      Base1.setRotationPoint(-1F, 23F, -18F);
      Base1.setTextureSize(512, 512);
      Base1.mirror = true;
      setRotation(Base1, 0F, 0F, 0F);
      Base2 = new ModelRenderer(this, 55, 0);
      Base2.addBox(0F, 0F, 0F, 1, 1, 22);
      Base2.setRotationPoint(-2F, 23F, -15F);
      Base2.setTextureSize(512, 512);
      Base2.mirror = true;
      setRotation(Base2, 0F, 0F, 0F);
      Base3 = new ModelRenderer(this, 0, 28);
      Base3.addBox(0F, 0F, 0F, 1, 1, 22);
      Base3.setRotationPoint(1F, 23F, -15F);
      Base3.setTextureSize(512, 512);
      Base3.mirror = true;
      setRotation(Base3, 0F, 0F, 0F);
      Base4 = new ModelRenderer(this, 98, 0);
      Base4.addBox(0F, 0F, 0F, 1, 1, 2);
      Base4.setRotationPoint(-0.5F, 23F, -20F);
      Base4.setTextureSize(512, 512);
      Base4.mirror = true;
      setRotation(Base4, 0F, 0F, 0F);
      Base5 = new ModelRenderer(this, 57, 24);
      Base5.addBox(0F, 0F, 0F, 1, 1, 16);
      Base5.setRotationPoint(-3F, 23F, -11F);
      Base5.setTextureSize(512, 512);
      Base5.mirror = true;
      setRotation(Base5, 0F, 0F, 0F);
      Base6 = new ModelRenderer(this, 57, 24);
      Base6.addBox(0F, 0F, 0F, 1, 1, 16);
      Base6.setRotationPoint(2F, 23F, -11F);
      Base6.setTextureSize(512, 512);
      Base6.mirror = true;
      setRotation(Base6, 0F, 0F, 0F);
      Base7 = new ModelRenderer(this, 106, 0);
      Base7.addBox(0F, 0F, 0F, 1, 1, 10);
      Base7.setRotationPoint(3F, 23F, -7F);
      Base7.setTextureSize(512, 512);
      Base7.mirror = true;
      setRotation(Base7, 0F, 0F, 0F);
      Base8 = new ModelRenderer(this, 104, 12);
      Base8.addBox(0F, 0F, 0F, 1, 1, 10);
      Base8.setRotationPoint(-4F, 23F, -7F);
      Base8.setTextureSize(512, 512);
      Base8.mirror = true;
      setRotation(Base8, 0F, 0F, 0F);
      Base9 = new ModelRenderer(this, 0, 52);
      Base9.addBox(0F, 0F, 0F, 2, 1, 21);
      Base9.setRotationPoint(-1F, 22F, -15F);
      Base9.setTextureSize(512, 512);
      Base9.mirror = true;
      setRotation(Base9, 0F, 0F, 0F);
      Base10 = new ModelRenderer(this, 49, 42);
      Base10.addBox(0F, 0F, 0F, 1, 1, 15);
      Base10.setRotationPoint(1F, 22F, -10F);
      Base10.setTextureSize(512, 512);
      Base10.mirror = true;
      setRotation(Base10, 0F, 0F, 0F);
      Base11 = new ModelRenderer(this, 49, 42);
      Base11.addBox(0F, 0F, 0F, 1, 1, 15);
      Base11.setRotationPoint(-2F, 22F, -10F);
      Base11.setTextureSize(512, 512);
      Base11.mirror = true;
      setRotation(Base11, 0F, 0F, 0F);
      Base12 = new ModelRenderer(this, 95, 26);
      Base12.addBox(0F, 0F, 0F, 1, 1, 10);
      Base12.setRotationPoint(2F, 22F, -7F);
      Base12.setTextureSize(512, 512);
      Base12.mirror = true;
      setRotation(Base12, 0F, 0F, 0F);
      Base13 = new ModelRenderer(this, 95, 26);
      Base13.addBox(0F, 0F, 0F, 1, 1, 10);
      Base13.setRotationPoint(-3F, 22F, -7F);
      Base13.setTextureSize(512, 512);
      Base13.mirror = true;
      setRotation(Base13, 0F, 0F, 0F);
      Base14 = new ModelRenderer(this, 98, 0);
      Base14.addBox(0F, 0F, 0F, 1, 1, 2);
      Base14.setRotationPoint(-0.5F, 22F, -17F);
      Base14.setTextureSize(512, 512);
      Base14.mirror = true;
      setRotation(Base14, 0F, 0F, 0F);
      Base15 = new ModelRenderer(this, 50, 61);
      Base15.addBox(0F, 0F, 0F, 2, 1, 14);
      Base15.setRotationPoint(-1F, 21F, -10F);
      Base15.setTextureSize(512, 512);
      Base15.mirror = true;
      setRotation(Base15, 0F, 0F, 0F);
      Base16 = new ModelRenderer(this, 95, 26);
      Base16.addBox(0F, 0F, 0F, 1, 1, 10);
      Base16.setRotationPoint(1F, 21F, -7F);
      Base16.setTextureSize(512, 512);
      Base16.mirror = true;
      setRotation(Base16, 0F, 0F, 0F);
      Base17 = new ModelRenderer(this, 95, 26);
      Base17.addBox(0F, 0F, 0F, 1, 1, 10);
      Base17.setRotationPoint(-2F, 21F, -7F);
      Base17.setTextureSize(512, 512);
      Base17.mirror = true;
      setRotation(Base17, 0F, 0F, 0F);
      Base18 = new ModelRenderer(this, 86, 43);
      Base18.addBox(0F, 0F, 0F, 2, 1, 10);
      Base18.setRotationPoint(-1F, 20F, -7F);
      Base18.setTextureSize(512, 512);
      Base18.mirror = true;
      setRotation(Base18, 0F, 0F, 0F);
      Base19 = new ModelRenderer(this, 85, 58);
      Base19.addBox(0F, 0F, 0F, 2, 1, 8);
      Base19.setRotationPoint(-1F, 19F, -6F);
      Base19.setTextureSize(512, 512);
      Base19.mirror = true;
      setRotation(Base19, 0F, 0F, 0F);
      Base20 = new ModelRenderer(this, 120, 26);
      Base20.addBox(0F, 0F, 0F, 1, 1, 8);
      Base20.setRotationPoint(1F, 20F, -6F);
      Base20.setTextureSize(512, 512);
      Base20.mirror = true;
      setRotation(Base20, 0F, 0F, 0F);
      Base21 = new ModelRenderer(this, 120, 26);
      Base21.addBox(0F, 0F, 0F, 1, 1, 8);
      Base21.setRotationPoint(-2F, 20F, -6F);
      Base21.setTextureSize(512, 512);
      Base21.mirror = true;
      setRotation(Base21, 0F, 0F, 0F);
      Base22 = new ModelRenderer(this, 98, 0);
      Base22.addBox(0F, 0F, 0F, 1, 1, 2);
      Base22.setRotationPoint(-0.5F, 21F, -12F);
      Base22.setTextureSize(512, 512);
      Base22.mirror = true;
      setRotation(Base22, 0F, 0F, 0F);
      Base23 = new ModelRenderer(this, 98, 0);
      Base23.addBox(0F, 0F, 0F, 1, 1, 2);
      Base23.setRotationPoint(-0.5F, 20F, -9F);
      Base23.setTextureSize(512, 512);
      Base23.mirror = true;
      setRotation(Base23, 0F, 0F, 0F);
      Base24 = new ModelRenderer(this, 137, 0);
      Base24.addBox(0F, 0F, 0F, 2, 4, 5);
      Base24.setRotationPoint(-1F, 15F, -4F);
      Base24.setTextureSize(512, 512);
      Base24.mirror = true;
      setRotation(Base24, 0F, 0F, 0F);
      Base25 = new ModelRenderer(this, 143, 13);
      Base25.addBox(0F, 0F, 0F, 2, 1, 14);
      Base25.setRotationPoint(-1F, 14F, -11F);
      Base25.setTextureSize(512, 512);
      Base25.mirror = true;
      setRotation(Base25, 0F, 0F, 0F);
      Base26 = new ModelRenderer(this, 163, 0);
      Base26.addBox(0F, 0F, 0F, 1, 1, 9);
      Base26.setRotationPoint(1F, 14F, -7F);
      Base26.setTextureSize(512, 512);
      Base26.mirror = true;
      setRotation(Base26, 0F, 0F, 0F);
      Base27 = new ModelRenderer(this, 163, 0);
      Base27.addBox(0F, 0F, 0F, 1, 1, 9);
      Base27.setRotationPoint(-2F, 14F, -7F);
      Base27.setTextureSize(512, 512);
      Base27.mirror = true;
      setRotation(Base27, 0F, 0F, 0F);
      Base28 = new ModelRenderer(this, 180, 39);
      Base28.addBox(0F, 0F, 0F, 2, 1, 30);
      Base28.setRotationPoint(-1F, 13F, -24F);
      Base28.setTextureSize(512, 512);
      Base28.mirror = true;
      setRotation(Base28, 0F, 0F, 0F);
      Base29 = new ModelRenderer(this, 139, 36);
      Base29.addBox(0F, 0F, 0F, 1, 1, 20);
      Base29.setRotationPoint(1F, 13F, -17F);
      Base29.setTextureSize(512, 512);
      Base29.mirror = true;
      setRotation(Base29, 0F, 0F, 0F);
      Base30 = new ModelRenderer(this, 139, 36);
      Base30.addBox(0F, 0F, 0F, 1, 1, 20);
      Base30.setRotationPoint(-2F, 13F, -17F);
      Base30.setTextureSize(512, 512);
      Base30.mirror = true;
      setRotation(Base30, 0F, 0F, 0F);
      Base31 = new ModelRenderer(this, 192, 0);
      Base31.addBox(0F, 0F, 0F, 1, 1, 13);
      Base31.setRotationPoint(2F, 13F, -13F);
      Base31.setTextureSize(512, 512);
      Base31.mirror = true;
      setRotation(Base31, 0F, 0F, 0F);
      Base32 = new ModelRenderer(this, 192, 0);
      Base32.addBox(0F, 0F, 0F, 1, 1, 13);
      Base32.setRotationPoint(-3F, 13F, -12F);
      Base32.setTextureSize(512, 512);
      Base32.mirror = true;
      setRotation(Base32, 0F, 0F, 0F);
      Base33 = new ModelRenderer(this, 200, 17);
      Base33.addBox(0F, 0F, 0F, 1, 1, 6);
      Base33.setRotationPoint(3F, 13F, -7F);
      Base33.setTextureSize(512, 512);
      Base33.mirror = true;
      setRotation(Base33, 0F, 0F, 0F);
      Base34 = new ModelRenderer(this, 200, 17);
      Base34.addBox(0F, 0F, 0F, 1, 1, 6);
      Base34.setRotationPoint(-4F, 13F, -7F);
      Base34.setTextureSize(512, 512);
      Base34.mirror = true;
      setRotation(Base34, 0F, 0F, 0F);
      Hammer1 = new ModelRenderer(this, 336, 17);
      Hammer1.addBox(0F, 0F, 0F, 1, 4, 1);
      Hammer1.setRotationPoint(4F, 13F, -3F);
      Hammer1.setTextureSize(512, 512);
      Hammer1.mirror = true;
      setRotation(Hammer1, 0F, 0F, 0F);
      Hammer2 = new ModelRenderer(this, 313, 0);
      Hammer2.addBox(0F, 0F, 0F, 1, 2, 3);
      Hammer2.setRotationPoint(4F, 11F, -4F);
      Hammer2.setTextureSize(512, 512);
      Hammer2.mirror = true;
      setRotation(Hammer2, 0F, 0F, 0F);
      Hammer3 = new ModelRenderer(this, 327, 0);
      Hammer3.addBox(0F, 0F, 0F, 1, 1, 1);
      Hammer3.setRotationPoint(4F, 12F, -1F);
      Hammer3.setTextureSize(512, 512);
      Hammer3.mirror = true;
      setRotation(Hammer3, 0F, 0F, 0F);
  }
  
  @Override
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    /*Base1.render(f5);
    Base2.render(f5);
    Base3.render(f5);
    Base4.render(f5);
    Base5.render(f5);
    Base6.render(f5);
    Base7.render(f5);
    Base8.render(f5);
    Base9.render(f5);
    Base10.render(f5);
    Base11.render(f5);
    Base12.render(f5);
    Base13.render(f5);
    Base14.render(f5);
    Base15.render(f5);
    Base16.render(f5);
    Base17.render(f5);
    Base18.render(f5);
    Base19.render(f5);
    Base20.render(f5);
    Base21.render(f5);
    Base22.render(f5);
    Base23.render(f5);
    Base24.render(f5);
    Base25.render(f5);
    Base26.render(f5);
    Base27.render(f5);
    Base28.render(f5);
    Base29.render(f5);
    Base30.render(f5);
    Base31.render(f5);
    Base32.render(f5);
    Base33.render(f5);
    Base34.render(f5);
    Hammer1.render(f5);
    Hammer2.render(f5);
    Hammer3.render(f5);*/
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  @Override
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

  public void renderModel(float f){
		Base1.render(f);
		Base2.render(f);
		Base3.render(f);
		Base4.render(f);
		Base5.render(f);
		Base6.render(f);
		Base7.render(f);
		Base8.render(f);
		Base9.render(f);
		Base10.render(f);
		Base11.render(f);
		Base12.render(f);
		Base13.render(f);
		Base14.render(f);
		Base15.render(f);
		Base16.render(f);
		Base17.render(f);
		Base18.render(f);
		Base19.render(f);
		Base20.render(f);
		Base21.render(f);
		Base22.render(f);
		Base23.render(f);
		Base24.render(f);
		Base25.render(f);
		Base26.render(f);
		Base27.render(f);
		Base28.render(f);
		Base29.render(f);
		Base30.render(f);
		Base31.render(f);
		Base32.render(f);
		Base33.render(f);
		Base34.render(f);
		Hammer1.render(f);
		Hammer2.render(f);
		Hammer3.render(f);
	}

}
